# Generated by Django 5.2.5 on 2025-08-19 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalarit', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='attended_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='class_attended',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kalarit.class'),
        ),
    ]
