# Generated by Django 5.2.5 on 2025-08-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalarit', '0006_feedback_attended_date_feedback_class_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='doubt',
            field=models.CharField(max_length=200, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='feedback',
            name='reply',
            field=models.CharField(max_length=200, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
