# Generated by Django 5.2.5 on 2025-08-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalarit', '0007_feedback_doubt_feedback_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='doubt',
        ),
    ]
