# Generated by Django 5.2.5 on 2025-08-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalarit', '0008_remove_feedback_doubt'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
