# Generated by Django 5.2.5 on 2025-08-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalarit', '0009_feedback_reply_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='events',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
