# Generated by Django 5.2.5 on 2025-08-19 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalarit', '0010_class_desc_class_image_events_desc_events_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('classid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kalarit.class')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('cardnumber', models.IntegerField(null=True)),
                ('cvv', models.IntegerField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('method', models.CharField(max_length=200, null=True)),
                ('classid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kalarit.class')),
            ],
        ),
    ]
