# Generated by Django 5.2.5 on 2025-08-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalarit', '0014_payment_eventid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollevent',
            old_name='classid',
            new_name='eventid',
        ),
    ]
