# Generated by Django 5.2.5 on 2025-08-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalarit', '0015_rename_classid_enrollevent_eventid'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollclass',
            name='attend',
            field=models.CharField(default='Absent', max_length=100, null=True),
        ),
    ]
