# Generated by Django 5.2.5 on 2025-08-20 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalarit', '0016_enrollclass_attend'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollevent',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kalarit.payment'),
        ),
    ]
