# Generated by Django 5.2.5 on 2025-08-21 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalarit', '0017_enrollevent_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='class_attended',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kalarit.enrollclass'),
        ),
    ]
