# Generated by Django 5.2.5 on 2025-08-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalarit', '0018_alter_feedback_class_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
