# Generated by Django 5.2.5 on 2025-08-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalarit', '0019_class_amount_events_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollclass',
            name='attend',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Present', 'Present'), ('Absent', 'Absent')], default='Not Started', max_length=100, null=True),
        ),
    ]
