# Generated by Django 5.2.5 on 2025-08-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalarit', '0020_alter_enrollclass_attend'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
